class_name DifficultyProfile
extends RefCounted

# Parametric progression for the 10 shipped levels. Each row is a full
# LevelConfig for a difficulty. Future levels (11+) are added by appending a
# row here — no code changes required anywhere else.
const LEVELS := {
	1: {
		"board_types": ["cat", "dog", "bird"],
		"count_per_type": 3,
		"columns": 5,
		"rows": 5,
		"occupancy_h": 0.6,
		"occupancy_v": 0.6,
		"layers": 2,
		"overlap": 0.45,
		"free_ratio": 0.55,
		"free_ratio_min": 0.4,
		"free_ratio_max": 0.7,
		"complexity": 1.0,
		"seed": 1001,
	},
	2: {
		"board_types": ["cat", "dog", "bird", "fish", "flower"],
		"count_per_type": 3,
		"columns": 6,
		"rows": 5,
		"occupancy_h": 0.67,
		"occupancy_v": 0.8,
		"layers": 2,
		"overlap": 0.5,
		"free_ratio": 0.5,
		"free_ratio_min": 0.4,
		"free_ratio_max": 0.65,
		"complexity": 2.0,
		"seed": 2001,
	},
	3: {
		"board_types": ["cat", "dog", "bird", "fish", "flower", "moon", "star"],
		"count_per_type": 3,
		"columns": 7,
		"rows": 6,
		"occupancy_h": 0.71,
		"occupancy_v": 0.67,
		"layers": 2,
		"overlap": 0.52,
		"free_ratio": 0.48,
		"free_ratio_min": 0.35,
		"free_ratio_max": 0.6,
		"complexity": 3.0,
		"seed": 3001,
	},
	4: {
		"board_types": ["cat", "dog", "bird", "fish", "flower", "moon", "star", "sun"],
		"count_per_type": 3,
		"columns": 7,
		"rows": 6,
		"occupancy_h": 0.71,
		"occupancy_v": 0.83,
		"layers": 3,
		"overlap": 0.56,
		"free_ratio": 0.45,
		"free_ratio_min": 0.3,
		"free_ratio_max": 0.55,
		"complexity": 4.0,
		"seed": 4001,
	},
	5: {
		"board_types": ["cat", "dog", "bird", "fish", "flower", "moon", "star", "sun"],
		"count_per_type": 3,
		"columns": 8,
		"rows": 6,
		"occupancy_h": 0.75,
		"occupancy_v": 0.83,
		"layers": 3,
		"overlap": 0.58,
		"free_ratio": 0.43,
		"free_ratio_min": 0.3,
		"free_ratio_max": 0.55,
		"complexity": 5.0,
		"seed": 5001,
	},
	6: {
		"board_types": ["cat", "dog", "bird", "fish", "flower", "moon", "star", "sun", "leaf"],
		"count_per_type": 3,
		"columns": 8,
		"rows": 7,
		"occupancy_h": 0.8,
		"occupancy_v": 0.75,
		"layers": 3,
		"overlap": 0.6,
		"free_ratio": 0.4,
		"free_ratio_min": 0.3,
		"free_ratio_max": 0.45,
		"complexity": 6.0,
		"seed": 6001,
	},
	7: {
		"board_types": ["cat", "dog", "bird", "fish", "flower", "moon", "star", "sun", "leaf", "heart"],
		"count_per_type": 3,
		"columns": 8,
		"rows": 7,
		"occupancy_h": 0.75,
		"occupancy_v": 0.86,
		"layers": 3,
		"overlap": 0.63,
		"free_ratio": 0.38,
		"free_ratio_min": 0.28,
		"free_ratio_max": 0.45,
		"complexity": 7.0,
		"seed": 7001,
	},
	8: {
		"board_types": ["cat", "dog", "bird", "fish", "flower", "moon", "star", "sun", "leaf", "heart"],
		"count_per_type": 3,
		"columns": 9,
		"rows": 7,
		"occupancy_h": 0.67,
		"occupancy_v": 0.86,
		"layers": 4,
		"overlap": 0.66,
		"free_ratio": 0.36,
		"free_ratio_min": 0.25,
		"free_ratio_max": 0.45,
		"complexity": 8.0,
		"seed": 8001,
	},
	9: {
		"board_types": ["cat", "dog", "bird", "fish", "flower", "moon", "star", "sun", "leaf", "heart", "gem"],
		"count_per_type": 3,
		"columns": 9,
		"rows": 7,
		"occupancy_h": 0.78,
		"occupancy_v": 0.86,
		"layers": 4,
		"overlap": 0.68,
		"free_ratio": 0.34,
		"free_ratio_min": 0.25,
		"free_ratio_max": 0.45,
		"complexity": 9.0,
		"seed": 9001,
	},
	10: {
		"board_types": ["cat", "dog", "bird", "fish", "flower", "moon", "star", "sun", "leaf", "heart", "gem", "crystal"],
		"count_per_type": 3,
		"columns": 10,
		"rows": 7,
		"occupancy_h": 0.7,
		"occupancy_v": 0.86,
		"layers": 4,
		"overlap": 0.7,
		"free_ratio": 0.32,
		"free_ratio_min": 0.22,
		"free_ratio_max": 0.4,
		"complexity": 10.0,
		"seed": 10001,
	},
	11: {
		"board_types": ["cat", "dog", "bird", "fish", "flower", "moon", "star", "sun", "leaf", "heart", "gem", "crystal"],
		"count_per_type": 3,
		"columns": 10,
		"rows": 7,
		"occupancy_h": 0.74,
		"occupancy_v": 0.86,
		"layers": 4,
		"overlap": 0.7,
		"free_ratio": 0.3,
		"free_ratio_min": 0.22,
		"free_ratio_max": 0.4,
		"complexity": 11.0,
		"seed": 11001,
	},
}

static func max_level() -> int:
	return LEVELS.size()

static func for_level(n: int) -> LevelConfig:
	var params: Dictionary = LEVELS.get(int(n), {})
	if params.is_empty():
		return null
	return LevelConfig.create(params)